---
name: qq

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release.yml
  schedule:
    - cron: 0 23 * * *

permissions: write-all

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: trigger
    outputs:
      trigger: ${{ steps.check.outputs.trigger }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: check if we need to trigger a build
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(wget -q https://github.com/flathub/com.qq.QQ/raw/refs/heads/master/com.qq.QQ.metainfo.xml -O - | grep -oP 'release version="\K[^"]*' | head -n 1)
          CURRENT="${VERSION//_/-}"
          if ! gh api "/repos/${{github.repository}}/releases/tags/$CURRENT" > /dev/null 2>&1; then
          echo "trigger=true" >> "$GITHUB_OUTPUT"
          echo "Build version=$CURRENT"
          else
          echo "trigger=false" >> "$GITHUB_OUTPUT"
          echo "Skip version=$CURRENT"
          fi
          echo "version=$CURRENT" >> "$GITHUB_OUTPUT"

  build:
    needs: trigger
    if: needs.trigger.outputs.trigger == 'true'
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: download
        env:
          VERSION: ${{ needs.trigger.outputs.version }}
        run: |
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_amd64_01.deb" > urls.txt
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_x86_64_01.rpm" >> urls.txt
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_x86_64_01.AppImage" >> urls.txt
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_arm64_01.deb" >> urls.txt
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_aarch64_01.rpm" >> urls.txt
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_arm64_01.AppImage" >> urls.txt
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_loongarch64_01.deb" >> urls.txt
          echo "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_${VERSION//-/_}_mips64el_01.deb" >> urls.txt
          cat urls.txt
          wget --no-verbose -i urls.txt
          rm -rf urls.txt
          ls -lh

      - name: rename
        run: |
          for file in QQ*; do
          name="${file//x86_64/amd64}"
          name="${name//aarch64/arm64}"
          architecture=$(echo "$name" | sed -E 's/QQ_[^_]+_[^_]+_([^_]+)_.*/\1/')
          ext=${file##*.}
          new_file="QQ-${{ needs.trigger.outputs.version }}-${architecture}.${ext}"
          mv "$file" "$new_file"
          done
          ls -lh

      - name: create tarball
        run: |
          chmod +x ./QQ-${{ needs.trigger.outputs.version }}-amd64.AppImage
          ./QQ-${{ needs.trigger.outputs.version }}-amd64.AppImage --appimage-extract
          mv squashfs-root qq
          tar -cJvf QQ-${{ needs.trigger.outputs.version }}-amd64.tar.xz qq
          sha1sum QQ-* > SHA1SUMS

      - name: create release note
        run: |
          echo '## SHA1 Checksums' > note.md
          echo '```' >> note.md  # Do not use double quotes
          cat SHA1SUMS >> note.md
          echo '```' >> note.md
          cat note.md

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.trigger.outputs.version }}
        run: |
          gh release create "${VERSION}" --notes-file note.md --title "QQ Linux ${VERSION}" --repo "${{github.repository}}" || true
          gh release upload "${VERSION}" ./QQ* --repo "${{github.repository}}"
          gh release upload "${VERSION}" ./SHA1SUMS --repo "${{github.repository}}"
          
  # https://github.com/liskin/gh-workflow-keepalive
  keepalive:
    if: github.event_name == 'schedule'
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Re-enable workflow
        run: |
          case "${GITHUB_WORKFLOW_REF:?}" in
          "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
          *) false ;;
          esac
          workflow="${GITHUB_WORKFLOW_REF%%@*}"
          workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
          echo "Re-enable $workflow"
          gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"

